name: Integration tests
on: [push]

jobs:
  test:
    name: Validate code quality
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          architecture: "x64"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install dev dependencies
        run: make install

      - name: Lint with flake8 and pyupgrade
        run: make lint

      - name: Validate basic functionality
        run: ./script.py --help
