name: Integration tests

on:
  push:
  schedule:
    - cron:  '0 5 * * *'

jobs:
  linting:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          architecture: 'x64'

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install module and its dependencies
        run: |
          uv venv venv
          venv/bin/uv install -r requirements.dev.txt

      - name: Lint with flake8 and pyupgrade
        run: |
          venv/bin/flake8 script.py
          venv/bin/pyupgrade --py312-plus script.py

      - name: Validate basic functionality
        run: ./script.py --help
